name: Update Checker

on:
  workflow_dispatch:
  schedule:
    - cron: '0 20 * * 0'  # 每周日 UTC 20:00 运行（北京时间 4:00 AM）

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo:
          - { name: "lede", url: "https://github.com/coolsnowwolf/lede", branch: "master" }
          - { name: "immo", url: "https://github.com/immortalwrt/immortalwrt", branch: "master" }
          - { name: "istore", url: "https://github.com/istoreos/istoreos", branch: "istoreos-22.03" }

    steps:
      - name: Checkout Repo & Get Commit Hash
        run: |
          git clone --depth 1 ${{ matrix.repo.url }} -b ${{ matrix.repo.branch }} repo
          cd repo
          latest_hash=$(git rev-parse HEAD)
          echo "commitHash=$latest_hash" >> $GITHUB_ENV

      - name: Restore Previous Commit Hash
        id: restore_hash
        run: |
          PREV_HASH_FILE=".commitHash-${{ matrix.repo.name }}"
          if [ -f "$PREV_HASH_FILE" ]; then
            prev_hash=$(cat "$PREV_HASH_FILE")
          else
            prev_hash="none"
          fi
          echo "prevCommitHash=$prev_hash" >> $GITHUB_ENV

      - name: Compare with Previous Commit Hash
        id: check_change
        run: |
          echo "Previous hash: ${{ env.prevCommitHash }}"
          echo "New hash: ${{ env.commitHash }}"
          if [ "${{ env.prevCommitHash }}" != "${{ env.commitHash }}" ]; then
            echo "updated=true" >> $GITHUB_ENV
            echo "${{ env.commitHash }}" > ".commitHash-${{ matrix.repo.name }}"
          else
            echo "updated=false" >> $GITHUB_ENV
          fi

      - name: Upload Latest Commit Hash
        uses: actions/upload-artifact@v3
        with:
          name: commit-hash-${{ matrix.repo.name }}
          path: .commitHash-${{ matrix.repo.name }}
          retention-days: 7

      - name: Trigger build for LEDE
        if: env.updated == 'true' && matrix.repo.name == 'lede'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
          repository: ${{ github.repository }}
          event-type: lede-update

      - name: Trigger build for IMMO
        if: env.updated == 'true' && matrix.repo.name == 'immo'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
          repository: ${{ github.repository }}
          event-type: immo-update

      - name: Trigger build for ISTORE
        if: env.updated == 'true' && matrix.repo.name == 'istore'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
          repository: ${{ github.repository }}
          event-type: istore-update

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 7
